# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2
# Personal info
name: Chanju Kim
title: Postdoctoral researcher @ DTU Fotonik
email: ckim@fotonik.dtu.dk
website: lightckim.github.io
# Dark Mode (true/false/never)
darkmode: false
# Social links
# twitter_username: facespics
github_username:  lightckim
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: eyeckim
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-8011-1904
#schoolar_username: Xg8JlCsAAAAJ
# Additional icon links
additional_links:
- title: Google scholar link
  icon: ai ai-google-scholar big-icon
  url: https://scholar.google.com/citations?user=Xg8JlCsAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
#google_analytics: "UA-42610718-0"
google_analytics: "UA-42610718-1"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Chanju and I'm a postdoctoral researcher at DTU Fotonik. 

  My field of expertise are in: <mark>Integrated photonics</mark>, <mark>Free-space optics</mark>, and <mark>Fiber optics</mark>
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Integrated Nonlinear Photonics
        link: https://orbit.dtu.dk/en/publications/integrated-nonlinear-photonics-theory-design-and-fabrication
        link_text: "PhD thesis | Integrated Nonlinear Photonics: Theory, Design, and Fabrication"
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: top-middle
        title: Solid-State Lasers
        #link: https://orbit.dtu.dk/en/publications/integrated-nonlinear-photonics-theory-design-and-fabrication
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: top-middle
        title: Time Stretch Imaging
        link: https://escholarship.org/uc/item/7j4068cd#author
        link_text: "MS thesis | High Throughput Web Inspection System using Time-stretch Real-time Imaging"
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical University of Denmark (DTU)
        link: https://www.fotonik.dtu.dk/english/research-groups/nanophotonic-devices
        link_text: Nanophotonic devices group
        sub_title: Postdoctoral researcher
        caption: 2021 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: Advanced Photonics Research Institute
        link: https://apri.gist.ac.kr
        link_text: Institute website
        sub_title: Researcher
        caption: 2014 - 2017
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay       
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical University of Denmark (DTU)
        caption: 2018 - 2021
        sub_title: PhD Photonic Engineering
        quote: >
          Established i
        description: | # this will include new lines to allow paragraphs
          Dut*.
      - layout: left
        title: University of California, Los Angeles
        caption: 2012 - 2013
        sub_title: MS Electrical Engineering
        quote: >
          Es reputation, and a
        description: | # this will include new lines to allow paragraphs
          During mime
      - layout: left
        title: Yonsei University
        caption: 2008 - 2012
        sub_title: BS Electrical & Electronic Engineering
        quote: >
          Es reputation, and a
        description: | # this will include new lines to allow paragraphs
          During mime
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
     Some of my other interests and hobbies are:
      - Making Kimchi

# Footer
footer_show_references: false
# references_title: References on request (Override references text)
# Build settings
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
 - jekyll-seo-tag